// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TaxForm.Models;

public partial class TaxFormReaderContext : DbContext
{
    public TaxFormReaderContext(DbContextOptions<TaxFormReaderContext> options)
        : base(options)
    {
    }

    public virtual DbSet<MsParameterValue> MsParameterValues { get; set; }

    public virtual DbSet<TrTax> TrTaxes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MsParameterValue>(entity =>
        {
            entity.ToTable("msParameterValue");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AlphaNumericValue).IsUnicode(false);
            entity.Property(e => e.Created).HasColumnType("date");
            entity.Property(e => e.Description).IsUnicode(false);
            entity.Property(e => e.NumericValue).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.Parameter)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TrTax>(entity =>
        {
            entity.ToTable("trTax");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("date");
            entity.Property(e => e.DasarPengenaanPajak).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.DocumentId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("DocumentID");
            entity.Property(e => e.FileName).IsUnicode(false);
            entity.Property(e => e.FilePath).IsUnicode(false);
            entity.Property(e => e.KetKodeObjekPajak)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.KodeObjekPajak)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.MasaPajak)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("date");
            entity.Property(e => e.NamaPemotong)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.NomorBuktiPotong)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.NomorKet)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Npwp)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NPWP");
            entity.Property(e => e.Pphdipotong)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("PPHDipotong");
            entity.Property(e => e.Remarks).IsUnicode(false);
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.StatusPelaporan).IsUnicode(false);
            entity.Property(e => e.StatusPph)
                .IsUnicode(false)
                .HasColumnName("StatusPPH");
            entity.Property(e => e.TanggalBuktiPotong).HasColumnType("date");
            entity.Property(e => e.TanggalKet).HasColumnType("date");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}