// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaxForm.Models;

public partial class TrTax
{
    public string DocumentId { get; set; }

    public decimal DasarPengenaanPajak { get; set; }

    public string KetKodeObjekPajak { get; set; }

    public string KodeObjekPajak { get; set; }

    public string MasaPajak { get; set; }

    public string NamaPemotong { get; set; }

    public string NomorBuktiPotong { get; set; }

    public string NomorKet { get; set; }

    public string Npwp { get; set; }

    public decimal Pphdipotong { get; set; }

    public DateTime TanggalBuktiPotong { get; set; }

    public DateTime TanggalKet { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime ModifiedDate { get; set; }

    public string CreatedBy { get; set; }

    public string ModifiedBy { get; set; }

    public string StatusPph { get; set; }

    public string StatusPelaporan { get; set; }

    public int Id { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public string Status { get; set; }

    public string Remarks { get; set; }
}